"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useState } from "react";

export default function AuthPanel({mode}:{mode:"signin"|"join"}){
  const params=useSearchParams();
  const router=useRouter();
  const [role,setRole]=useState(params.get("role")==="investor"?"investor":"founder");
  const [message,setMessage]=useState("");
  const submit=(e:FormEvent)=>{e.preventDefault();setMessage("Preview mode: opening your private product tour…");window.setTimeout(()=>router.push(`/dashboard?role=${role}`),600)};
  const signin=mode==="signin";
  return <main className="auth-page"><div className="auth-shell glass"><section className="auth-story"><Link href="/" className="wordmark">BYLLD <b>X</b></Link><div><h1>{signin?<>WELCOME<br/><em>BACK.</em></>:<>BUILD YOUR<br/><em>NEXT MOVE.</em></>}</h1><p>{signin?"Return to your focused network, opportunities and conversations.":"Create the role-specific profile that helps the right people understand your ambition."}</p></div><small>Private profiles · Protected ideas · Responsible discovery</small></section><form className="auth-form" onSubmit={submit}><span className="eyebrow">{signin?"Secure member access":"Create your account"}</span><h2>{signin?"Sign in to BYLLD X":"Choose your permanent role"}</h2><p>{signin?"This preview uses fictional data. Production authentication connects through verified email, Google or GitHub.":"One email creates one account. Your Founder or Investor role cannot be changed later."}</p><div className="social-buttons"><button type="button" onClick={()=>setMessage("Google sign-in activates after Supabase credentials are connected.")}>G&nbsp; Continue with Google</button><button type="button" onClick={()=>setMessage("GitHub sign-in activates after Supabase credentials are connected.")}>◉&nbsp; Continue with GitHub</button></div><div className="divider">OR CONTINUE WITH EMAIL</div>{!signin&&<div className="role-choice"><label className="role-option"><input type="radio" name="role" checked={role==="founder"} onChange={()=>setRole("founder")}/><b>Founder</b><small>Publish ideas and discover aligned investors.</small></label><label className="role-option"><input type="radio" name="role" checked={role==="investor"} onChange={()=>setRole("investor")}/><b>Investor</b><small>Discover founders and protected opportunities.</small></label></div>}{!signin&&<label className="field"><span>Full name</span><input required autoComplete="name" placeholder="Your full name"/></label>}<label className="field"><span>Email address</span><input required type="email" autoComplete="email" placeholder="you@example.com"/></label><label className="field"><span>Password</span><input required minLength={8} type="password" autoComplete={signin?"current-password":"new-password"} placeholder="Minimum 8 characters"/></label>{!signin&&<label className="consent"><input type="checkbox" required/><span>I accept the <Link href="/terms">Terms of Service</Link> and <Link href="/privacy">Privacy Policy</Link>.</span></label>}<button className="button" type="submit">{signin?"Open product preview":"Start onboarding"} →</button>{message&&<p role="status" style={{color:"#0c55ed",fontWeight:700,marginBottom:0}}>{message}</p>}<div className="auth-links">{signin?<><Link href="/join">Create an account</Link><a href="#" onClick={(e)=>{e.preventDefault();setMessage("Password reset emails activate with your Supabase project.")}}>Forgot password?</a></>:<><Link href="/signin">Already have an account?</Link><Link href="/">Back home</Link></>}</div></form></div></main>
}
