import Link from "next/link";
export default function LegalPage({kind}:{kind:"terms"|"privacy"|"safety"}){
 const copy={
  terms:{title:"Terms of Service",intro:"These launch-preview terms explain the boundary of BYLLD X and the responsibilities of every member.",sections:[["Platform role","BYLLD X is a discovery and communication platform. It is not an investment adviser, broker, marketplace, escrow service or guarantor. Investments, agreements, payments and equity transactions happen outside BYLLD X."],["Member responsibility","Members must provide accurate information, protect account access, respect confidential material and perform their own legal, technical and financial checks before acting on any opportunity."],["Acceptable use","Illegal content, fraud, scams, harassment, spam, fake identities, stolen ideas and inappropriate content are prohibited. BYLLD X may warn, suspend or ban accounts that break these rules."],["Protected ideas","A connection can unlock protected founder information for an investor. Access does not transfer ownership, create confidentiality terms or guarantee accuracy. Founders should share only information suitable for this context."],["Subscriptions","Premium is purchased for one month, does not renew automatically and is non-refundable. The current checkout is a clearly marked test flow until a payment provider is configured."],["Disputes and liability","Members remain responsible for agreements and dealings conducted outside BYLLD X. BYLLD X is not responsible for disputes between founders and investors."]]},
  privacy:{title:"Privacy Policy",intro:"BYLLD X is designed around internal profiles, controlled idea access and minimal public exposure.",sections:[["Information collected","Account identity, permanent role, profile content, discovery preferences, ideas, saved profiles, connections, messages, notifications, reports, subscription status and security events may be processed to operate the platform."],["Internal discovery","Founder and Investor profiles are searchable only inside BYLLD X. Authenticated profile pages and protected ideas are marked for no-indexing and are never intended for public search engines."],["Sensitive data","Email addresses, authentication data, payment data, private messages and protected idea information are not exposed publicly. Service credentials remain server-side and access is enforced by database policies."],["Use of information","Data is used to provide role-specific discovery, matching, usage limits, connections, messaging, safety enforcement and account administration. BYLLD X does not send profile-view or profile-save notifications."],["Retention and deletion","Account deletion removes ideas, connections, saved profiles and messages immediately, subject to legally required payment-receipt retention."],["Contact","Questions about privacy can be sent to privacy@bylldx.in."]]},
  safety:{title:"Safety & Platform Rules",intro:"Trust depends on clear boundaries, careful access and decisive action against abuse.",sections:[["Before you connect","Review public context carefully. Do not share credentials, authentication codes or financial account access. A profile or connection is not an endorsement by BYLLD X."],["Before you invest","Perform independent legal, financial, technical and identity checks. Use qualified professional advice and signed agreements outside BYLLD X."],["Blocking","Blocking disconnects both accounts, locks the conversation, removes protected-idea access and prevents future requests until unblocked."],["Reporting","Profiles and ideas can be reported for spam, harassment, fraud or scam, fake identity, inappropriate content, stolen content or another documented concern. Reports are confidential from the reported user."],["Enforcement","BYLLD X may issue a warning, remove an idea, temporarily suspend access, permanently ban an account or delete an account when rules are broken."],["Emergency or criminal matters","Contact relevant authorities directly when safety, fraud or illegal activity requires urgent intervention. BYLLD X is not an emergency service."]]}
 }[kind];
 return <main className="legal-page"><header className="legal-header"><Link href="/" className="wordmark">BYLLD <b>X</b></Link><Link href="/" className="inline-link">← Back home</Link></header><article className="legal-card glass"><span className="eyebrow">Last updated 6 August 2026</span><h1>{copy.title}</h1><p className="notice">{copy.intro}</p>{copy.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<p>Launch note: This document is a product-ready draft and should be reviewed by qualified Indian legal counsel before the public commercial launch.</p></article></main>
}
